spring:
  datasource:

    url: ${DB_URL:jdbc:mysql://localhost:3306/db_financeiro}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:GrpIcr#2740@@}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true